spring.application.name=aitaskmanager

# Server Configuration
server.port=8080

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aitaskdb
spring.datasource.username=postgres
spring.datasource.password=sole@2006

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (PostgreSQL specific)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SECRET KEY
jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey
